#file: noinspection ComposeUnknownKeys
version: "3.9"
services:
  scout:
    build:
      context: ./
      # noinspection ComposeUnknownKeys,ComposeUnknownKeys
      dockerfile_inline: |
          FROM docker.io/library/python:3.11.3-alpine
          COPY requirements_compose.txt /tmp
          RUN pip install -r /tmp/requirements_compose.txt
          COPY . /scout
          RUN pip install /scout[postgresql]
          CMD ["python3", "-m", "Scout.scout"]

    env_file: .env
    depends_on:
      - db
    networks:
      - public
      - db
    environment:
      DB_DIALECT: 'postgresql'
      DB_DRIVER: 'psycopg'
      DB_TABLE: 'scout'
      DB_USER: 'postgres'
      DB_PASS: 'postgres'
      DB_HOST: 'db'
  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/pgsql/data
    networks:
      - db

volumes:
  db:

networks:
  public:
    internal: false
  db:
    name: scout_db
    attachable: true
    internal: true

